
import os
import numpy as np
from bio_embeddings.embed.prottrans_t5_embedder import ProtTransT5XLU50Embedder

os.environ['TMPDIR'] = 'D:\\TUM\\protein_prediction\\DeepEntropy\\data\\models'

embedders = []
sequence = "MALLHSARVLSGVASAFHPGLAAAASARASSWWAHVEMGPPDPILGVTEAYKRDTNSKKMNLGVGAYRDDNGKPYVLPSVRKAEAQIAAKGLDKEYLPIGGLAEFCRASAELALGENSEVVKSGRFVTVQTISGTGALRIGASFLQRFFKFSRDVFLPKPSWGNHTPIFRDAGMQLQSYRYYDPKTCGFDFTGALEDISKIPEQSVLLLHACAHNPTGVDPRPEQWKEIATVVKKRNLFAFFDMAYQGFASGDGDKDAWAVRHFIEQGINVCLCQSYAKNMGLYGERVGAFTVICKDADEAKRVESQLKILIRPMYSNPPIHGARIASTILTSPDLRKQWLQEVKGMADRIIGMRTQLVSNLKKEGSTHSWQHITDQIGMFCFTGLKPEQVERLTKEFSIYMTKDGRISVAGVTSGNVGYLAHAIHQVTK"

embedders.append(ProtTransT5XLU50Embedder())

embeddings = []
for embedder in embedders:
    embedding = embedder.embed(sequence)
    embeddings.append(embedding)

for embedding in embeddings:
    print(np.array(embedding).shape)
